### ISSUE TITLE
Widescreen patch does not work

### ISSUE THREAD

**Issue by apisitsamerwai** [igorciz777/RBC1GP-Translation-Pipeline#4] opened 2024-08-22 10:52 UTC
**Describe the bug**
I have tried either enabled integrated widescreen patcher in the graphic menu from PCSX2 and third-party widescreen patcher Pnach cheat from Tokyo Xtreme Racer Archive.

Both does not work as I tried enabled the patcher from both cheat and PCSX2 integrated widescreen in graphic menu beforehand until launch the patched the iso or enabled after launch the patched iso.

I doubted if I was following the installation method wrong.

**To Reproduce**

**Expected behavior**

**Screenshots**
![Racing Battle - C1 Grand Prix_SLPM-65897_20240822172621](https://github.com/user-attachments/assets/7dccb2e6-eb05-4020-ae5e-c4d6c1f24673)
![Screenshot 2024-08-22 172736](https://github.com/user-attachments/assets/b657f339-0536-4c44-8d20-ed08d6fd36b8)
![Screenshot 2024-08-22 172825](https://github.com/user-attachments/assets/6eb7330f-c2bc-4fbd-b474-6b8dc907aced)

**Device**
Describe the way you are playing:
-Windows 11, Ryzen 2700, Gigabyte GTX1050ti 4gb
-PCSX2, 2.1.102

**Additional context**
I saw you have widescreen patch enabled in your Vlog #2 video. how could I make it works for mine?

**Comment by igorciz777** [comment] 2024-08-22 12:03
You either put the .pnach translation file into the `patches` folder instead of `cheats`
or replaced the `SLPM_658.97` executable file with the patched one, which is NOT advised to do for running the game on PCSX2

Here is what should be displayed when starting the game:
![aaa](https://github.com/user-attachments/assets/1f5d81d1-d94f-4388-84fa-43259fb9896b)

Closing the issue as its a non-replicable personal bug on your end, most likely caused by installing the patch wrong.
Give the README file a proper read and try again

**Closed by igorciz777** 2024-08-22 12:03 UTC
Labels: bug
